// Keeping track of the types of categories actions
export const CATEGORIES_ACTION_TYPES = {
  // SET_CATEGORIES: 'category/SET_CATEGORIES_MAP',
  FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCES: 'category/FETCH_CATEGORIES_SUCCES',
  FETCH_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED',
}
